# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/refs/heads/main/configuration-schema.json
package: cms
output: client.gen.go
generate:
  models: true
  client: true
additional-imports:
  - package: github.com/reearth/reearth-cms/server/pkg/id
  - package: github.com/reearth/reearth-cms/server/pkg/types
